# Generated by Django 2.2.12 on 2021-01-07 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollster',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
        migrations.AddField(
            model_name='pollster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollsters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestocksheepcycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_sheep_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestocksaleschannel',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_sales_channel', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockreproduction',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_reproduction', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockrabbitcycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_rabbit_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockpoultrycycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_poultry_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockpigcycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_pig_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketing', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockllamacycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_llama_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockhealth',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_health', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockgoatcycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_goat_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockbovinecycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_bovine_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockbeekeepingcycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_beekeeping_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockaquaculturecycle',
            name='production_livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_aquaculture_cycle', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockanimalpens',
            name='production_livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_animal_pens', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='livestockanimalfeeding',
            name='production_livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_animal_feeding', to='producer.ProductionLivestock'),
        ),
        migrations.AddField(
            model_name='installationwell',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_well', to='producer.ProductionInstallation'),
        ),
        migrations.AddField(
            model_name='installationbarn',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_barn', to='producer.ProductionInstallation'),
        ),
        migrations.AddField(
            model_name='agroindustrialtools',
            name='production_agroindustrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agroindustrial_tools', to='producer.ProductionAgroindustrial'),
        ),
        migrations.AddField(
            model_name='agroindustrialhandmandeproduct',
            name='production_agroindustrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agroindustrial_handmande_product', to='producer.ProductionAgroindustrial'),
        ),
        migrations.AddField(
            model_name='agroindustrialfoodproduct',
            name='production_agroindustrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agroindustrial_food_product', to='producer.ProductionAgroindustrial'),
        ),
        migrations.AddField(
            model_name='agriculturalsaleschannel',
            name='production_agricultural',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_sales_channel', to='producer.ProductionAgricultural'),
        ),
        migrations.AddField(
            model_name='agriculturalpests',
            name='production_agricultural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_pests', to='producer.ProductionAgricultural'),
        ),
        migrations.AddField(
            model_name='agriculturalharvest',
            name='production_agricultural',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_harvest', to='producer.ProductionAgricultural'),
        ),
        migrations.AddField(
            model_name='agriculturalclimatic',
            name='production_agricultural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_climatic', to='producer.ProductionAgricultural'),
        ),
        migrations.AddField(
            model_name='agriculturalattendance',
            name='production_agricultural',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_attendance', to='producer.ProductionAgricultural'),
        ),
        migrations.AddField(
            model_name='activityworker',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_worker', to='producer.ProducerActivity'),
        ),
    ]
